server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://192.168.110.32:3306/agri_big_data?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 082415
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-circular-references: true

hadoop:
  hdfs:
    block:
      size: 67108864
    replication: 3
    use:
      datanode:
        hostname: localhost
    buffer:
      size: 4096
    uri: hdfs://localhost:9000
    user: root
    root-dir: /user/hadoop
    connection:
      required=false: false
      required: false
    impl: org.apache.hadoop.hdfs.DistributedFileSystem

hive:
  url: jdbc:hive2://192.168.1.192:10000
  username: root
  password:
  database: default
  driver: org.apache.hive.jdbc.HiveDriver
  connection:
    timeout: 30
    required: false



# JWT配置
security:
  jwt:
    token:
      secret-key: MzK4xNjQ5MDIzODckMTY0OTAyMzg3Jib20kMTYNDkwMjM4JiYzJDE2NDkwMjM4a27nczNzJiJjb20kMTY0OTAyMzg3QHNzY2jYW4
      expire-length: 86400000 # 24小时，单位：毫秒

