# 应用配置
server:
  port: 8001
  servlet:
    context-path: /api
  tomcat:
    max-threads: 200
    max-connections: 10000

spring:
  application:
    name: hadoop2-kafka-ws
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # MySQL数据源配置
  datasource:
    url: jdbc:mysql://nas:3306/agri_data?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 082415
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10

# MySQL传感器配置
mysql:
  sensor:
    database: agri_data
    table: sensor_data

# Kafka配置
kafka:
  bootstrap:
    servers: shiguang:9092,nas:9092
  consumer:
    group:
      id: agriculture-data-group
  topics:
    agriculture-sensor-data: agriculture-sensor-data
    stock-data: stock-data

# Spark配置
spark:
  master: local[*]
  batch:
    duration: 5
  enabled: true
  app:
    name: AgricultureDataProcessing

# 数据生成器配置
data:
  generator:
    enabled: true
    interval: 3000

# 传感器数据配置
sensor:
  # 是否启用传感器模块
  enabled: true
  # 数据采集参数
  data:
    batch-size: 100
    interval: 5000
    # 数据存储配置
    storage:
      # 存储目标: mysql, hive, both
      target: mysql
      # 是否启用Hive存储
      hive-enabled: false
      # 是否启用MySQL存储
      mysql-enabled: true
  # 模拟配置
  simulation:
    enabled: false
  # kafka主题
  kafka:
    topic: agriculture-sensor-data

# Hive配置
hive:
  url: jdbc:hive2://shiguang:10000
  driver: org.apache.hive.jdbc.HiveDriver
  username: root
  password: 
  sensor:
    database: agri_data
    table: sensor_data



