server:
  port: 8000

app:
  host: hadoop
spring:
  application:
    name: agriculture-sensor-processor
  # 添加MySQL数据库配置
  datasource:
    url: jdbc:mysql://${app.host}:3306/agri_big_data?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 082415
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Kafka配置
kafka:
  bootstrap.servers: ${app.host}:9092
  topic: agriculture-sensor-data
  group.id: agriculture-sensor-group

# WebSocket配置  
websocket:
  host: 0.0.0.0
  port: 8090

# Spark配置
spark:
  app.name: AgricultureSensorProcessor
  master: local[*] 
  serializer: org.apache.spark.serializer.KryoSerializer
  streaming.batch.duration: 5

# 异常检测阈值
anomaly:
  threshold:
    temperature: 5.0
    humidity: 10.0
    soil_moisture: 15.0
    light_intensity: 200.0
    co2: 100.0

debug: false