# 应用配置
server:
  port: 8001
  servlet:
    context-path: /api
  tomcat:
    max-threads: 200
    max-connections: 10000

spring:
  application:
    name: hadoop2-kafka-ws
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


# Kafka配置
kafka:
  bootstrap:
    servers: shiguang:9092,nas:9092
  consumer:
    group:
      id: agriculture-data-group
  topics:
    agriculture-sensor-data: agriculture-sensor-data
    stock-data: stock-data

# Spark配置
spark:
  master: local[*]
  batch:
    duration: 5
  enabled: true
  app:
    name: AgricultureDataProcessing

# 数据生成器配置
data:
  generator:
    enabled: true
    interval: 3000

# 传感器数据配置
sensor:
  # 是否启用传感器模块
  enabled: true
  # 数据采集参数
  data:
    batch-size: 100
    interval: 5000
  # 模拟配置
  simulation:
    enabled: false
  # kafka主题
  kafka:
    topic: agriculture-sensor-data



